name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    environment:
      name: pypi
      url: https://pypi.org/p/govuk-search-mcp

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup environment
        uses: ./.github/actions/setup-env
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
